### ISSUE TITLE
Issues Starting program

### ISSUE THREAD

**Issue by v00d0079** [jcardama/csgo-market-sniper#39]
Heres the traceback Im getting: any fixes?

Traceback (most recent call last):
  File "c:\Users\Scotts Gamer\Desktop\csgo-market-sniper\csgo-market-sniper.py", line 9, in <module>
    from driver import init_driver
    from seleniumwire import webdriver
  File "c:\Users\Scotts Gamer\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\webdriver.py", line 28, in <module>
    from seleniumwire import backend, utils
  File "c:\Users\Scotts Gamer\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "c:\Users\Scotts Gamer\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "c:\Users\Scotts Gamer\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\handler.py", line 5, in <module>
    from seleniumwire import har
  File "c:\Users\Scotts Gamer\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "c:\Users\Scotts Gamer\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "c:\Users\Scotts Gamer\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tls.py", line 15, in <module>
    import seleniumwire.thirdparty.mitmproxy.options
  File "c:\Users\Scotts Gamer\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\options.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import optmanager
  File "c:\Users\Scotts Gamer\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\optmanager.py", line 9, in <module>
    import blinker._saferef
ModuleNotFoundError: No module named 'blinker._saferef'

**Comment by sargija** [comment]
same problem here, it worked, but later ran into this issue
